name: Java CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:5.7
        env:
          MYSQL_ROOT_PASSWORD: senha230600
          MYSQL_DATABASE: db_venda
        ports:
          - 3306:3306
        options: >-
          --health-cmd="mysqladmin ping -h localhost -u root -psenha230600 --silent"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=3

    steps:
    - name: Check out repository
      uses: actions/checkout@v2

    - name: Set up JDK 8
      uses: actions/setup-java@v2
      with:
        java-version: '8'
        distribution: 'adopt'

    - name: Download JUnit, Hamcrest, and MySQL Connector/J
      run: |
        mkdir -p lib
        curl -L -o lib/junit-4.13.2.jar https://search.maven.org/remotecontent?filepath=junit/junit/4.13.2/junit-4.13.2.jar
        curl -L -o lib/hamcrest-core-1.3.jar https://search.maven.org/remotecontent?filepath=org/hamcrest/hamcrest-core/1.3/hamcrest-core-1.3.jar
        curl -L -o lib/mysql-connector-java-8.0.26.jar https://repo1.maven.org/maven2/mysql/mysql-connector-java/8.0.26/mysql-connector-java-8.0.26.jar

    - name: Wait for MySQL
      run: |
        while ! mysqladmin ping -h "127.0.0.1" -u root -psenha100 --silent; do
          echo "Waiting for database connection..."
          sleep 2
        done

    - name: Set up database
      run: |
        mysql -h "127.0.0.1" -u root -psenha230600 db_venda < Script_BD_venda.sql

    - name: Compile and test
      run: |
        find . -name "*.java" > sources.txt
        mkdir -p build/classes
        javac -cp "lib/*" -d build/classes @sources.txt
        java -cp "build/classes:lib/*" org.junit.runner.JUnitCore $(find build/classes -name "*Test*.class" | sed 's/build\/classes\///' | sed 's/\//./g' | sed 's/\.class//')

    - name: Archive test results
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-results
        path: build/test-results
